### ISSUE TITLE
Docker Image Versioned Tags

### ISSUE THREAD

**Issue by cablespaghetti** [single-spa/import-map-deployer#61] opened 2020-07-06 13:04 UTC
Hi,

I've noticed that the Docker image on Docker Hub only has a "latest" tag. It would be great if new tagged releases could generate a new tag on Docker Hub as well, so it is possible for us to run a specific version in Production.

Thanks!

**Comment by joeldenning** [comment] 2020-07-06 18:39
I completely agree - happy to do this manually for previous releases. But would be interested in incorporating this into a `prepublishOnly` script.

**Comment by cablespaghetti** [comment] 2020-07-06 18:58
Hi Joel,

Given the images are built using Docker Hub Builds it should just be a case of configuring it to build on tags. I'm not very familiar with prePublishOnly scripts to know how that would work unfortunately.

Thanks
Sam

**Comment by joeldenning** [comment] 2020-07-06 18:58
Ah good point - we could have CI do this when it detects a new tag. I'll investigate

**Comment by joeldenning** [comment] 2020-07-07 03:23
I tried it with CI (https://github.com/single-spa/import-map-deployer/commit/aedd4ecf1cdc4b886b9a597d0160cad4cd9a6295) but it turned out to be somewhat tricky to get it working in Travis. I gave up once I ran into a problem where travis considered a push to master with new tags to sometimes be the master branch and sometimes not to be the master branch.

So I ended up implementing this as a `postpublish` script that will run whenever I publish a new version. This means that the person publishing it must login to docker hub and have access to the repo. But it was easier to set up. It will now automatically run in all future publishes.

I am closing this issue since it's set up for future versions - let me know if you'd like me to push up a tag of a previous version that you're interested in using. I will link to the tag on docker hub once it finishes pushing (it has taken over 15 minutes!!). I documented how to use it at https://github.com/single-spa/import-map-deployer/commit/ca56b935a7ef8ca87d7343c97c061ea4dd4a08f7

**Closed by joeldenning** 2020-07-07 03:23 UTC

**Comment by joeldenning** [comment] 2020-07-07 03:45
Here is the `v2.2.1` tag - https://hub.docker.com/layers/singlespa/import-map-deployer/v2.2.1/images/sha256-d725ec45d3977e4decbfa119514fc537c9ad847df26bdda180c188ee4a809316?context=repo

**Comment by joeldenning** [comment] 2020-07-07 04:55
Ah I just realized that docker hub can do this very easily - switched over to using that.

**Comment by cablespaghetti** [comment] 2020-07-08 09:43
Great thanks! :)

**Comment by joeldenning** [comment] 2020-07-13 17:48
Just confirmed that this is not working. See https://hub.docker.com/repository/docker/singlespa/import-map-deployer/builds.

<img width="1276" alt="image" src="https://user-images.githubusercontent.com/5524384/87336234-bf649a00-c4fe-11ea-9e58-edf807eefd81.png">


I likely just configured docker hub incorrectly. If anyone spots anything wrong in that screenshot, please share.

**Comment by joeldenning** [comment] 2020-07-13 18:12
Just fixed it. First successful auto build for a git tag is at https://hub.docker.com/repository/registry-1.docker.io/singlespa/import-map-deployer/builds/6e27cf34-2b5e-42f5-8289-1a515b9523e2
